# Generated by Django 2.2.1 on 2019-07-02 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190608_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0, 'too Less'), django.core.validators.MaxValueValidator(1000, 'too more')]),
        ),
    ]
